import { describe, expect, it } from 'vitest';
import fixtures from './fixtures.json';
import { RNG } from './rng';
import { Sim, runReplay, type Config, type Replay } from './engine';

interface Fixture {
  name: string;
  seed: number;
  boosters: string[];
  config: Config;
  boards: number[][];
  replay: Replay;
  result: { outcome: string; score: number; loot: number; vaultReached: number; vaultsCracked: number; multiplier: number; totalMoves: number };
  steps: Array<{ vault: number; move: number; loot: number; movesLeft: number; objectives: { key: number; laser: number; camera: number }; state: string; grid: number[] }>;
}

const all = fixtures as unknown as Fixture[];

describe('mulberry32 matches the Go reference', () => {
  it('produces the reference sequence for seed 82938122', () => {
    const r = new RNG(82938122);
    expect([r.next(), r.next(), r.next(), r.next(), r.next()]).toEqual([1885756853, 1183468422, 931213250, 3325039468, 2478020766]);
  });
  it('handles seed 0 and 0xFFFFFFFF', () => {
    const z = new RNG(0);
    expect([z.next(), z.next(), z.next()]).toEqual([1144304738, 1416247, 958946056]);
    const m = new RNG(0xffffffff);
    expect([m.next(), m.next(), m.next()]).toEqual([3850105811, 813802916, 3073704848]);
  });
});

describe('golden fixtures generated by the Go engine', () => {
  it('has fixtures', () => {
    expect(all.length).toBeGreaterThan(0);
  });

  for (const fx of all) {
    it(`${fx.name}: boards, every step and the final score match`, () => {
      const rng = new RNG(fx.seed);
      let step = 0;
      for (let vi = 0; vi < fx.replay.vaults.length; vi++) {
        const sim = new Sim(rng, fx.config, vi, fx.boosters);
        expect(sim.grid, `${fx.name} vault ${vi + 1} initial board`).toEqual(fx.boards[vi]);
        for (let mi = 0; mi < fx.replay.vaults[vi].moves.length; mi++) {
          sim.apply(fx.replay.vaults[vi].moves[mi]);
          const want = fx.steps[step++];
          expect(want.vault).toBe(vi);
          expect(want.move).toBe(mi);
          expect(sim.loot, `${fx.name} v${vi + 1} m${mi + 1} loot`).toBe(want.loot);
          expect(sim.movesLeft, `${fx.name} v${vi + 1} m${mi + 1} movesLeft`).toBe(want.movesLeft);
          expect(sim.objectives).toEqual(want.objectives);
          expect(sim.state).toBe(want.state);
          expect(sim.grid, `${fx.name} v${vi + 1} m${mi + 1} grid`).toEqual(want.grid);
        }
      }
      expect(step).toBe(fx.steps.length);

      const res = runReplay(fx.config, fx.seed, fx.boosters, fx.replay);
      expect(res).toEqual(fx.result);
      expect(res.score).toBe(fx.replay.clientScore);
    });
  }
});

describe('replay validation', () => {
  const fx = all[0];
  it('rejects a tampered seed', () => {
    expect(() => runReplay(fx.config, fx.seed + 1, fx.boosters, fx.replay)).toThrow();
  });
  it('rejects illegal chains', () => {
    const sim = new Sim(new RNG(1), fx.config, 0, []);
    sim.grid.fill(3);
    sim.grid[10] = 0;
    sim.grid[20] = 6;
    expect(sim.validatePath([0, 1])).not.toBeNull();
    expect(sim.validatePath([0, 1, 0])).not.toBeNull();
    expect(sim.validatePath([9, 10, 11])).not.toBeNull();
    expect(sim.validatePath([0, 1, 3])).not.toBeNull();
    expect(sim.validatePath([19, 20, 21])).not.toBeNull();
    expect(sim.validatePath([0, 1, 2])).toBeNull();
    expect(sim.validatePath([0, 8, 16])).toBeNull();
  });
  it('guard chains refund the move and unlock adjacent locks', () => {
    const sim = new Sim(new RNG(1), fx.config, 0, []);
    sim.grid.fill(3);
    sim.grid[7] = sim.grid[8] = sim.grid[9] = 5;
    sim.grid[14] = 6;
    sim.movesLeft = 5;
    const res = sim.apply([7, 8, 9]);
    expect(res.bonusMove).toBe(true);
    expect(sim.movesLeft).toBe(5);
    expect(res.loot).toBe(90);
    expect(res.unlocked).toEqual([14]);
    expect(sim.grid.includes(-1)).toBe(false);
  });
});
